language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Zu0ZD0U3yQH3miBhGVviI8FWD93qBPGP8hepPfcpTHFpy+wYTE54RsubmzPLjOZBqol8qBumBsEoMiq3+5CNVlCCgZ1FVNonwrO958IAz/LAatholQowGcEAFa9x2YE6borxwQpzyUpEbcHDHc4O0DnbsMXXKdYTZ6XtquRcSshWlWtFDLTdkPP8yU/EkWYPpCE7WMT+PUP6iA0KoncXS7jalpZCv6WnYWgP73/O3RFxmDXY+0T8uWw5Z5JdEPFu7pvGhnBEReRAOtXcAGJ/+Hk1CunFWx1DrVmER0eVgeeiFEePTuxsFsBTruqwgUY7ShGmsSx5S1N/1h1cQxTcn/J8apbgrqNz9U6R8bZPYRsoQxpK7ARYqPztJWR27JM67QkXjm23Kvk9BcWfJq2XT4mn5BrJgGaCAlalCfnZLLVcVRTDBCHiw7+CmywvgDSlg3XKrDT2J8tHlUMhTwNz+kaffWCD9s1vMQU/XFSDHmIJI950zS5N5uF73HuM3EebAaOMiEoXrfJIdQ+BTBK4OLcp1Y7+5WI9u/AXZQuxeIFNaHzK2c7SqT3vXcbmuVLwG8tTDtojmMuEF242aBnHiMZYIcM1SE5NKLz7HobANN9eu7I7NKuQdxrPgPtgo4NXriWeXdCQ1ejh3PZ5UYhgEZhxzzCFhpFzRJibnflDwVs=
